import Head from "next/head";
import { Configuration, UploadManager } from "upload-js-full";

const uploadManager = new UploadManager(
  new Configuration({
    fetchApi: fetch,
    apiKey: "XXX", // e.g. "secret_xxxxx"
  })
);

export default function Home() {
  const upload = async (file: File) => {
    await uploadManager.upload({
      accountId: "XXX",
      data: file,
    });
  };

  const onFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!e.target.files) return;

    const file = e.target.files[0];

    if (!file) return;

    await upload(file);
  };

  return (
    <>
      <Head>
        <title>Upload.io PoC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ padding: 40 }}>
        <input type="file" onChange={(e) => void onFileChange(e)} />
      </main>
    </>
  );
}
